influx:
  url: http://influxdb.nixserver.io
  org: Test
  bucket: testing
  batch_size: 50
  interval: 10
streams:
  BTCUSDT-1m:
    symbol: btcusdt
    interval: 1m
  ETHUSDT-1m:
    symbol: ethusdt
    interval: 1m
